export default {	

	race_track: {
		simtype: 'AvoidEdgesSimulation',
		name: 'Race Track',
		num_boids: 60,
		timeout: 36,
		volume:4000000,
		punishment: 2,
		max_segment_spread: 170,
		max_mutation: 0.3,
		cullpct: 0.3,
		food_proximity_bonus: 1,
		// tunnel: true,
		spiral:true,
		rounds:100,
		poop:false,
		ignore_other_boids:true,
		ignore_lifecycle:true,
		no_marks:true,
		no_combat:true,
		score_on_travel:true,
		score_on_proximity:true,
	},
	
	obstacle_course: {
		simtype: 'AvoidEdgesSimulation',
		name: 'Obstacle Course',
		num_boids: 60,
		timeout: 12,
		volume:4000000,
		punishment: 2,
		max_segment_spread: 170,
		joints: 10,
		max_mutation: 0.3,
		cullpct: 0.3,
		angle_spread: 0,
		food_proximity_bonus: 1,
		tunnel: true,
		// spiral:true,
		rounds:100,
		poop:false,
		ignore_other_boids:true,
		ignore_lifecycle:true,
		no_marks:true,
		no_combat:true,
		score_on_travel:true,
		score_on_proximity:true,
	},

	food_training_sim_easy: {
		simtype: 'FoodChaseSimulation',
		name: 'Food Chase - Easy',
		num_boids: 50,
		// random_boid_pos: true,
		// random_food_pos: true,
		timeout: 16,
		// min_score: 5,
		max_mutation: 0.1,
		// you can separately define DNA and brain mutations, in case you want just one or the other
		// dna_mutation_rate: 0.1,
		// brain_mutation_rate: 0.1,
		num_rocks: 0,
		num_plants: 0,
		species:'random',
		cullpct: 0.4,
		edibility: 1,
		volume: 2500000,
		current: 0,
		num_foods: 1,
		food_speed: 70,
		food_bounce_margin: 300,
		food_friction: false,
		food_value:3000,
		food_lifespan: 10,
		phantomfood: true,
		min_avg_score:500,
		min_avg_score_rounds: 10,
		rounds:150,
		poop:false,
		ignore_other_boids:true,
		ignore_lifecycle:true,
		no_marks:true,
		no_combat:true,
		score_on_travel:true,
		score_on_proximity:true,
	},
	
	food_training_sim_medium: {
		simtype: 'FoodChaseSimulation',
		name: 'Food Chase - Medium',
		num_boids: 80,
		// random_boid_pos: true,
		// random_food_pos: true,
		timeout: 30,
		// min_score: 5,
		max_mutation: 0.1,
		// you can separately define DNA and brain mutations, in case you want just one or the other
		// dna_mutation_rate: 0.1,
		// brain_mutation_rate: 0.1,
		num_rocks: 1,
		num_plants: 0,
		species:'random',
		cullpct: 0.3,
		edibility: 1,
		volume: 4000000,
		current: 0,
		num_foods: 2,
		food_speed: 125,
		food_bounce_margin: 300,
		food_friction: false,
		food_value:1000,
		food_lifespan: 10,
		phantomfood: true,
		min_avg_score:500,
		min_avg_score_rounds: 10,
		rounds:150,
		poop:false,
		ignore_other_boids:true,
		ignore_lifecycle:true,
		no_marks:true,
		no_combat:true,
		score_on_travel:false,
		score_on_proximity:true,
	},
	
	food_training_sim_hard: {
		simtype: 'FoodChaseSimulation',
		name: 'Food Chase - Hard',
		num_boids: 60,
		// random_boid_pos: true,
		// random_food_pos: true,
		timeout: 60,
		// min_score: 5,
		max_mutation: 0.2,
		// you can separately define DNA and brain mutations, in case you want just one or the other
		// dna_mutation_rate: 0.1,
		// brain_mutation_rate: 0.1,
		num_rocks: 3,
		num_plants: 0,
		species:'random',
		cullpct: 0.2,
		edibility: 1,
		volume: 4500000,
		current: 0,
		num_foods: 3,
		food_speed: 400,
		food_bounce_margin: 300,
		food_friction: false,
		food_value:300,
		food_lifespan: 7,
		phantomfood: true,
		min_avg_score:600,
		min_avg_score_rounds: 10,
		rounds:180,
		poop:false,
		ignore_other_boids:true,
		ignore_lifecycle:true,
		no_marks:true,
		no_combat:true,
		score_on_travel:false,
		score_on_proximity:true,
	},
	
	finishing_school: {
		simtype: 'FinishingSimulation',
		name: 'Finishing School',
		num_boids: 80,
		num_foods: 40,
		num_rocks: 8,
		timeout: 60,
		max_mutation: 0.2,
		cullpct: 0.2,
		volume:12000000,
		rounds:60,
		poop:true,
		ignore_other_boids:false,
		on_bite_ignore:true,
		edibility: 1,
		permafood:true,
		food_speed: 0.00001,
		random_food_pos: true,
		random_boid_pos: true,
		random_boid_angle: true,
		food_bounce_margin: 0,
		food_friction: true,
		food_value:300,
		ignore_lifecycle:true,
		no_marks:false,
		no_combat:false,
		score_on_travel:false,
		score_on_proximity:false,
	},
		
	turning_training_easy: {
		simtype: 'TurningSimulation',
		name: 'Steering - Easy',
		num_boids: 100,
		num_foods: 1,
		timeout: 1.6,
		max_mutation: 0.3,
		angle_spread: 0.7, // radians
		cullpct: 0.12,
		distance: 500,
		volume:5000000,
		distance_variance: 0.4,
		min_avg_score:90,
		min_avg_score_rounds: 7,
		rounds:100,
		poop:false,
		ignore_other_boids:true,
		on_bite_ignore:true,
		edibility: 1,
		ignore_lifecycle:true,
		no_marks:true,
		no_combat:true,
	},
	turning_training_medium: {
		simtype: 'TurningSimulation',
		name: 'Steering - Medium',
		num_boids: 100,
		num_foods: 2,
		timeout: 5,
		max_mutation: 0.2,
		angle_spread: 1.0, // radians
		cullpct: 0.18,
		distance: 500,
		volume:10000000,
		distance_variance: 0.3,
		min_avg_score:88,
		min_avg_score_rounds: 10,
		rounds:100,
		poop:false,
		ignore_other_boids:true,
		on_bite_ignore:true,
		edibility: 1,
		ignore_lifecycle:true,
		no_marks:true,
		no_combat:true,
	},
	turning_training_hard: {
		simtype: 'TurningSimulation',
		name: 'Steering - Hard',
		num_boids: 100,
		num_foods: 5,
		timeout: 16,
		num_rocks:1,
		max_mutation: 0.2,
		angle_spread: 1, // radians
		cullpct: 0.25,
		distance: 450,
		volume:26000000,
		distance_variance: 0.2,
		min_avg_score:88,
		min_avg_score_rounds: 7,
		rounds:120,
		poop:false,
		ignore_other_boids:true,
		on_bite_ignore:true,
		edibility: 1,
		ignore_lifecycle:true,
		no_marks:true,
		no_combat:true,
	},
	turning_training_xhard: {
		simtype: 'TurningSimulation',
		name: 'Steering - Extra Hard',
		num_boids: 100,
		num_foods: 5,
		num_rocks: 5,
		timeout: 20,
		max_mutation: 0.2,
		angle_spread: 1, // radians
		cullpct: 0.25,
		distance: 450,
		volume:26000000,
		distance_variance: 0.2,
		min_avg_score:86,
		min_avg_score_rounds: 7,
		rounds:150,
		poop:false,
		ignore_other_boids:true,
		on_bite_ignore:true,
		edibility: 1,
		ignore_lifecycle:true,
		no_marks:true,
		no_combat:true,
	},
	treasure_hunt_easy: {
		simtype: 'FoodChaseSimulation',
		name: 'Treasure Hunt - Easy',
		num_boids: 80,
		num_foods: 25,
		num_rocks: 6,
		timeout: 120,
		max_mutation: 0.3,
		cullpct: 0.2,
		volume:15000000,
		rounds:120,
		poop:false,
		ignore_other_boids:true,
		on_bite_ignore:true,
		edibility: 1,
		permafood:true,
		food_speed: 0.00001,
		random_food_pos: true,
		food_bounce_margin: 0,
		food_friction: true,
		food_value:1000,
		ignore_lifecycle:true,
		no_marks:true,
		no_combat:true,
		score_on_travel:false,
		score_on_proximity:false,
	},
	treasure_hunt_hard: {
		simtype: 'FoodChaseSimulation',
		name: 'Treasure Hunt - Hard',
		num_boids: 80,
		num_foods: 50,
		num_rocks: 20,
		timeout: 120,
		max_mutation: 0.3,
		cullpct: 0.2,
		volume:16000000,
		rounds:250,
		poop:false,
		ignore_other_boids:true,
		on_bite_ignore:true,
		edibility: 1,
		permafood:true,
		food_speed: 0.00001,
		random_food_pos: true,
		food_bounce_margin: 0,
		food_friction: true,
		food_value:1000,
		ignore_lifecycle:true,
		no_marks:true,
		no_combat:true,
		score_on_travel:false,
		score_on_proximity:false,
	},	
	treasure_hunt_perpetual: {
		simtype: 'FoodChaseSimulation',
		name: 'Treasure Hunt - Perpetual',
		num_boids: 80,
		num_foods: 50,
		num_rocks: 20,
		timeout: 120,
		max_mutation: 0.3,
		cullpct: 0.2,
		volume:18000000,
		rounds:10000000,
		poop:false,
		ignore_other_boids:true,
		on_bite_ignore:true,
		edibility: 1,
		permafood:true,
		food_speed: 0.00001,
		random_food_pos: true,
		food_bounce_margin: 0,
		food_friction: true,
		food_value:1000,
		ignore_lifecycle:true,
		no_marks:true,
		no_combat:true,
		score_on_travel:false,
		score_on_proximity:false,
	},	
	learning_gym: {
		simtype: 'TurningSimulation',
		name: 'Learning Gym - Perpetual',
		num_boids: 60,
		num_foods: 8,
		num_rocks: 0,
		timeout: 20,
		max_mutation: 0.0,
		cullpct: 0.02,
		volume:30000000,
		rounds:10000000,
		poop:false,
		ignore_other_boids:true,
		on_bite_ignore:true,
		edibility: 1,
		permafood:true,
		food_speed: 0.00001,
		random_food_pos: true,
		food_bounce_margin: 0,
		food_friction: true,
		food_value:1000,
		ignore_lifecycle:true,
		no_marks:true,
		no_combat:true,
		score_on_travel:false,
		score_on_proximity:false,
	},	
	natural_tank: {
		simtype: 'NaturalTankSimulation',
		name: 'Natural Tank',
		num_boids: 30,
		random_boid_pos: true,
		safe_spawn: true,
		timeout: 0,
		max_mutation: 0.2,
		num_rocks: 0,
		num_plants: 60,
		species:'random',
		volume: 10000000,
		current: 0.1,
		num_foods: 0,
		food_friction: true,
		tide: 600,
		random_boid_angle: true,
		randomize_age:false,
		random_terrain:true,
		no_combat:false,
		invasives: 5,
		invasives_freq: 500,
		matter_diffusion_freq: 33,
		matter_diffusion_strength: 0.1,
		speciation_rate: 1/30,
	},
	peaceful_tank: {
		simtype: 'NaturalTankSimulation',
		name: 'Peaceful Tank',
		num_boids: 30,
		random_boid_pos: true,
		safe_spawn: true,
		timeout: 0,
		// min_score: 5,
		max_mutation: 0.2,
		num_rocks: 0,
		num_plants: 60,
		species:'random',
		volume: 10000000,
		current: 0.1,
		num_foods: 0,
		food_friction: true,
		tide: 600,
		random_boid_angle: true,
		randomize_age:false,
		random_terrain:true,
		no_combat:true,
		invasives: 5,
		invasives_freq: 500,
		matter_diffusion_freq: 33,
		matter_diffusion_strength: 0.1,
		speciation_rate: 1/30,
	},
			
	petri_dish: {
		simtype: 'FoodChaseSimulation',
		name: 'Petri Dish',
		num_boids: 1,
		random_boid_pos: true,
		random_food_pos: true,
		timeout: 0,
		// min_score: 5,
		max_mutation: 0,
		num_rocks: 5,
		num_plants: 0,
		edibility: 1,
		volume: 2000000,
		current: 0,
		num_foods: 1,
		food_speed: 0,
		food_bounce_margin: 200,
		food_friction: true,
		food_value:1000,
		poop:true,
		ignore_other_boids:false,
		randomize_age:false,
	},
			
	combat: {
		simtype: 'CombatSimulation',
		name: 'Combat',
		num_boids: 120,
		segments: 3,
		random_boid_pos: true,
		random_boid_angle: true,
		timeout: 16,
		cullpct: 0.3,
		max_mutation: 0.3,
		num_rocks: 0,
		num_plants: 0,
		edibility: 1,
		volume: 10000000,
		current: 0,
		num_foods: 0,
		poop:false,
		ignore_other_boids:false,
		randomize_age:false,
		ignore_lifecycle:true,
		no_marks:true,
	}
};